"""
Procedural AI-themed flavor (Tier 3.7).

Wir sind ein KI-Unternehmen — entsprechend lebt das Spiel von LLM-styled
Variation in Event-Feed, Sabotage-Titeln und Postmortems. Da es im MVP keinen
echten LLM-Call gibt, würfeln wir aus reichen Templates. Output liest sich
wie ein müder Senior-Engineer, der einen Incident-Report dictiert.

Public API:
- pick_event_text(category, **ctx) → str
- generate_postmortem(summary) → str   (multi-line markdown-flavored block)
"""

import random
from typing import Final

# --- event-feed flavor pools -----------------------------------------------

_VIBE_INTROS: Final[tuple[str, ...]] = (
    "Vibe Coder hat",
    "Ein KI-Pair-Programmer hat",
    "Ein Junior mit Cursor hat",
    "Der Vibe-Coding-Workflow hat",
    "Promptly™ hat",
)

_FLAVOR_SABOTAGE: Final[dict[str, tuple[str, ...]]] = {
    "ci_cd_red": (
        "CI/CD steht. Niemand weiss warum. Alle wissen warum.",
        "Pipeline rot. Greens wieder schwer zu kriegen — gestern noch alles cool.",
        "main ist rot. Vermutlich ein 'kleiner Refactor'.",
        "CI hatte einen Hallucinations-Anfall.",
    ),
    "flaky_tests": (
        "Tests sind heute optional. Sagt jedenfalls die Suite.",
        "Flaky Tests entdeckt. Alle ignorieren sie professionell.",
        "Tests laufen nur noch im Vibe-Modus.",
    ),
    "merge_conflict_storm": (
        "Merge Conflict Storm. Wir hatten Plaene fuer heute.",
        "Drei PRs haben gleichzeitig main geforked. Klassisch.",
        "Jemand hat git push --force gerollt. Ohne PR.",
    ),
    "coffee_outage": (
        "Kaffeemaschine meldet 418: I'm a teapot.",
        "Kitchen ist trocken. Pager-Engineering startet jetzt.",
        "Espresso-Service offline. Productivity drops in 3, 2, ...",
    ),
    "mandatory_meeting": (
        "Mandatory Meeting. Es haette eine Email sein koennen.",
        "Calendar bombt mit OKR-Sync. Engineering blockt.",
        "Standup ueber Standups beginnt jetzt.",
    ),
    "fake_customer_request": (
        "Ein Kunde hat 'nur eine kleine Aenderung' gemeldet.",
        "Sales has questions. Always.",
        "Customer wants Feature X. Was nicht im Backlog ist. Klar.",
    ),
    "lights_out": (
        "PagerDuty-Storm. Sichtweite reduziert auf 'Notruf'.",
        "Server Room im roten Licht. Es flackert, aber stilvoll.",
        "Monitoring-Dashboard schlaegt Wellen.",
    ),
    "comms_outage": (
        "Slack ist down. Productivity steigt kurz.",
        "Comms-Outage. Endlich Ruhe. Endlich Chaos.",
        "Niemand kann mehr koordinieren. Niemand will.",
    ),
}

_FLAVOR_REPAIR: Final[tuple[str, ...]] = (
    "Repair done. Der Pager schweigt — bis jetzt.",
    "Outage behoben. Standup laeuft schon.",
    "Service wieder up. Niemand erinnert sich an Logs.",
)

_FLAVOR_VOTE_KICK: Final[tuple[str, ...]] = (
    "Das Team hat entschieden. Performance Improvement Plan ausgeliefert.",
    "Du wurdest aus dem Sprint genommen. Gruende: 'vibes'.",
    "Force-Reboot ausgefuehrt. Coredumped.",
)

_FLAVOR_BODY_FOUND: Final[tuple[str, ...]] = (
    "Jemand hat nicht 'gut' geschlafen. Genauer: gar nicht mehr.",
    "Stale process gefunden. Reboot-Diagnose ausstehend.",
    "Body discovered. Postmortem in Standup naechste Woche.",
)


def pick_event_text(category: str, *, default: str = "", rng: random.Random | None = None) -> str:
    """Return a single random flavor line for the given event category. Falls
    back to ``default`` if no pool exists. Pools are merged with the legacy
    sabotage texts so we never lose the canonical message — the WS event feed
    already keeps both."""
    r = rng or random
    pool: tuple[str, ...] = ()
    if category in _FLAVOR_SABOTAGE:
        pool = _FLAVOR_SABOTAGE[category]
    elif category == "repair":
        pool = _FLAVOR_REPAIR
    elif category == "vote_kick":
        pool = _FLAVOR_VOTE_KICK
    elif category == "body_found":
        pool = _FLAVOR_BODY_FOUND
    if not pool:
        return default
    return r.choice(pool)


# --- postmortem generator --------------------------------------------------

_POSTMORTEM_OPENERS: Final[tuple[str, ...]] = (
    "## Postmortem — Release {n}\n",
    "## Incident Postmortem — Sprint {n}\n",
    "## RCA — Release Window {n}\n",
)

_AI_NARRATOR_OPENINGS: Final[tuple[str, ...]] = (
    "Generated by Claude (vibes-only mode). ",
    "Auto-drafted by an LLM at 3 AM. ",
    "Synthesized from logs, screams, and Slack threads. ",
)

_OUTRO_LINES: Final[tuple[str, ...]] = (
    "Action items: noch keine. Wir vergessen es bis zum naechsten Sprint.",
    "Lessons learned: die gleichen wie letztes Mal.",
    "Next steps: post-coffee retro.",
    "Follow-up: 'kleine Aenderung' wird ab sofort als Feature klassifiziert.",
)


def _bullets_from_summary(summary: dict) -> list[str]:
    """Turn the per-round summary dict into prose bullets."""
    lines: list[str] = []
    rp = summary.get("releaseProgress", 0)
    ps = summary.get("pipelineStability", 0)
    inc = summary.get("incidents", 0)
    lines.append(f"- Release-Progress am Ende: **{rp} %** (Pipeline {ps} %, Incidents {inc} %).")
    sab_total = summary.get("sabotagesTriggered", 0)
    rep_total = summary.get("repairsCompleted", 0)
    lines.append(
        f"- Sabotagen ausgeloest: **{sab_total}** — Repairs durchgezogen: **{rep_total}**."
    )
    kills = summary.get("kills", 0)
    if kills:
        lines.append(f"- Force-Reboots im Office: **{kills}**. Coredumps zaehlen.")
    awards = summary.get("awards") or []
    for award in awards[:4]:
        lines.append(f"- *{award['title']}*: **{award['playerName']}** — {award['reason']}.")
    return lines


def generate_postmortem(summary: dict, rng: random.Random | None = None) -> str:
    """Compose a multi-line postmortem string from the round summary. The
    output is intentionally LLM-styled — it's the kind of thing a tired
    senior engineer would dictate in retro."""
    r = rng or random
    n = summary.get("roundNumber", 1)
    opener = r.choice(_POSTMORTEM_OPENERS).format(n=n)
    narrator = r.choice(_AI_NARRATOR_OPENINGS)
    winner = summary.get("winner") or "?"
    if winner == "release_team":
        verdict = (
            "Das Release-Team hat es ueber die Linie gebracht. Knapp, mit "
            "viel Kaffee und weniger Wuerde als erhofft."
        )
    elif winner == "chaos_agents":
        verdict = (
            "Chaos-Agenten haben uns die Pipeline auseinandergenommen. "
            "Kein Release. Es war 'genau wie letzten Sprint'."
        )
    else:
        verdict = "Das Spiel endete unentschieden. Wir tun so, als waere das ein Erfolg."

    bullets = "\n".join(_bullets_from_summary(summary))
    outro = r.choice(_OUTRO_LINES)

    return f"{opener}{narrator}{verdict}\n\n{bullets}\n\n{outro}"
